# Atributos e métodos de arrays Numpy

In [1]:
#importando numpy
import numpy as np

In [32]:
km = [44410., 5712., 37123., 0., 225757.]
anos = [2003, 1991, 1990, 2019, 2006]

dados = np.array([[44410., 5712., 37123., 0., 225757.], [2003., 1991., 1990., 2019., 2006.]])

In [33]:
dados

array([[ 44410.,   5712.,  37123.,      0., 225757.],
       [  2003.,   1991.,   1990.,   2019.,   2006.]])

In [4]:
type(dados)

numpy.ndarray

ndarray.shape

In [5]:
#mostra linhas e colunas
dados.shape

(2, 5)

ndarray.ndim

In [6]:
#mostra as dimensões
dados.ndim

2

ndarray.size

In [7]:
#retorna o numero de elementos do array
dados.size

10

ndarray.dtype

In [8]:
#os tipos de elementos do array
dados.dtype

dtype('float64')

ndarray.T

In [9]:
#transpoe as linhas e coluna, invertendo as posições de linha/colua, para: coluna/linha
dados.transpose()

array([[ 44410.,   2003.],
       [  5712.,   1991.],
       [ 37123.,   1990.],
       [     0.,   2019.],
       [225757.,   2006.]])

# Métodos

ndarray,tolist

In [10]:
#gera uma lista do array
dados.tolist()

[[44410.0, 5712.0, 37123.0, 0.0, 225757.0],
 [2003.0, 1991.0, 1990.0, 2019.0, 2006.0]]

# *ndarray.reshape(shape, [order])*

In [11]:
#retorna um array que contem os mesmos dados com uma nova forma

contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
contador.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
contador.reshape((5,2), order='C')

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [14]:
contador.reshape((2,5), order='F')

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [15]:
km 

[44410.0, 5712.0, 37123.0, 0.0, 225757.0]

In [16]:
anos

[2003.0, 1991.0, 1990.0, 2019.0, 2006.0]

In [17]:
i_carros = np.array([km, anos]).reshape((2, 5))

In [18]:
i_carros

array([[ 44410.,   5712.,  37123.,      0., 225757.],
       [  2003.,   1991.,   1990.,   2019.,   2006.]])

In [19]:
i_carros.T

array([[ 44410.,   2003.],
       [  5712.,   1991.],
       [ 37123.,   1990.],
       [     0.,   2019.],
       [225757.,   2006.]])

# *ndarray.resize(new_shape[,refcheck])*

In [20]:
dados_new = dados.copy()

In [21]:
dados_new

array([[ 44410.,   5712.,  37123.,      0., 225757.],
       [  2003.,   1991.,   1990.,   2019.,   2006.]])

In [34]:
dados_new.resize((3, 5), refcheck=False)
dados_new

array([[4.44100000e+04, 5.71200000e+03, 3.71230000e+04, 0.00000000e+00,
        2.25757000e+05],
       [2.00300000e+03, 1.99100000e+03, 1.99000000e+03, 2.01900000e+03,
        2.00600000e+03],
       [2.77562500e+03, 2.04000000e+02, 1.28010345e+03,            nan,
        1.73659231e+04]])

In [35]:
#inserindo no indice 2 os a media de km calculado pelo indice  0 e 1
dados_new[2] = dados_new[0] / (2019 - dados_new[1])

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


In [36]:
dados_new

array([[4.44100000e+04, 5.71200000e+03, 3.71230000e+04, 0.00000000e+00,
        2.25757000e+05],
       [2.00300000e+03, 1.99100000e+03, 1.99000000e+03, 2.01900000e+03,
        2.00600000e+03],
       [2.77562500e+03, 2.04000000e+02, 1.28010345e+03,            nan,
        1.73659231e+04]])