# Calculo com slice em arrays

In [27]:
import numpy as np

peso = np.array([96, 70, 54, 80])
altura = np.array([1.93, 1.60, 1.90, 1.70])

dados = np.array([[96, 70, 54, 80], [1.93, 1.60, 1.90, 1.70]])

In [28]:
dados

array([[96.  , 70.  , 54.  , 80.  ],
       [ 1.93,  1.6 ,  1.9 ,  1.7 ]])

In [40]:
dados[:, :5][0] / (dados[:, :5][1] ** 2)

array([25.77250396, 27.34375   , 14.95844875, 27.6816609 ])

In [36]:
dados[:, 2][0]

54.0

In [43]:
dados_1 = np.array([['Roberto', 'casado', 'masculino'], ['Sheila', 'solteiro', 'feminino'], ['Bruno', 'solteiro', 'masculino'], ['Rita', 'casado', 'feminino']])
dados_1

array([['Roberto', 'casado', 'masculino'],
       ['Sheila', 'solteiro', 'feminino'],
       ['Bruno', 'solteiro', 'masculino'],
       ['Rita', 'casado', 'feminino']], dtype='<U9')

In [122]:
#booleano mostra local em que aparecem os masculinos
a = dados_1[::2, 2] == 'masculino'

In [123]:
a

array([ True,  True])

In [124]:
a = dados_1[:, 2] == 'masculino'

In [125]:
a

array([ True, False,  True, False])

In [118]:
#[:(todas as linhas):(de 2 em 2) :(até o indice 1), ]
dados_1[::2, :2] 

array([['Roberto', 'casado'],
       ['Bruno', 'solteiro']], dtype='<U9')

# FIM