# Operações aritiméticas com arrays Numpy

In [25]:
import numpy as np

In [2]:
km = [44410., 5712., 37123., 0., 25757.]
anos = [2003, 1991, 1990, 2019, 2006]

In [3]:
# idade = 2019 - anos
# lista não suport calculo de inteiros e lista

In [4]:
km = np.array([44410., 5712., 37123., 0., 25757.])
anos = np.array([2003, 1991, 1990, 2019, 2006])

In [5]:
idade = 2019 - anos

In [6]:
idade

array([16, 28, 29,  0, 13])

# Operações entre arrays

In [7]:
km_media = km / idade

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [8]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

In [10]:
44410 / (2019 - 2003)

2775.625

In [11]:
5712 / (2019 - 1991)

204.0

# Operações com arrays de duas dimensões

In [14]:
dados = np.array([km, anos])

In [16]:
dados.shape

(2, 5)

In [17]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [18]:
dados[0]

array([44410.,  5712., 37123.,     0., 25757.])

In [19]:
dados[1]

array([2003., 1991., 1990., 2019., 2006.])

In [20]:
km_media = dados[0] / (2019 - anos)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [23]:
km_media

array([2775.625     ,  204.        , 1280.10344828,           nan,
       1981.30769231])

# Utilizando slice

In [28]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
contador[1:6]

array([1, 2, 3, 4, 5])

In [30]:
contador[1::2]

array([1, 3, 5, 7, 9])

In [31]:
contador[::2]

array([0, 2, 4, 6, 8])

In [33]:
contador[1:8:2]

array([1, 3, 5, 7])

# Slice nos dados

In [34]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [37]:
dados[:, 1:3][0]

array([ 5712., 37123.])

In [38]:
dados[:, 1:3][1]

array([1991., 1990.])

In [39]:
dados[:, 1:3][0] / (2019 - dados[:, 1:3][1])

array([ 204.        , 1280.10344828])

# Indexação com array booleano

In [40]:
contador = np.arange(10)

In [41]:
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
contador > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [43]:
contador[contador > 5]

array([6, 7, 8, 9])

In [51]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [52]:
dados[1] > 2000

array([ True, False, False,  True,  True])

In [54]:
dados[[1], dados[1] > 2000]

array([2003., 2019., 2006.])

# Fim