In [1]:
import numpy as np

# Indexação "np.array"


In [2]:
contador = np.arange(10)
contador

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
contador[-1]

9

In [4]:
contador[::2]

array([0, 2, 4, 6, 8])

In [5]:
contador[1:7:1]

array([1, 2, 3, 4, 5, 6])

In [6]:
item = 6
index = item - 1
contador[index]

5

In [19]:
#unindo 2 arrays

km = np.array([44410.0, 5712.0, 37123.0, 0, 25757.0])
anos = np.array([2003, 1991, 1990, 2019, 2006])

dados = np.array([km, anos])
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [20]:
#[linha, indice]
dados[1, 2]

1990.0

In [21]:
#[:selecionando todas as linhas, selecionando do indice de 1 a 3]
dados[:, 1:4]

array([[ 5712., 37123.,     0.],
       [ 1991.,  1990.,  2019.]])

In [22]:
#[:selecionando todas as linhas, selecionando do indice de 1 a 2] e [filtrando as linhas]
dados[:, 1:3][0] / (2019 - dados[:, 1:3][1])

array([ 204.        , 1280.10344828])

# Outros testes de indexação e slice

In [23]:
dados

array([[44410.,  5712., 37123.,     0., 25757.],
       [ 2003.,  1991.,  1990.,  2019.,  2006.]])

In [25]:
# [selecionando todas as linhas, trazendo da linha com indice 1 anos maiores que 2000]
dados[:, dados[1] > 2000]

array([[44410.,     0., 25757.],
       [ 2003.,  2019.,  2006.]])